@extends('layouts.app')
@section('title', 'Contact & Locations | JJK Gurukulam Trust Kerala')
@section('description', 'Contact JJK Gurukulam Trust and find travel details for the children’s Gurukulam in Thiruvananthapuram and Shanti Nilayam in Thrissur.')
@section('content')
@include('partials.page-hero',['eyebrow'=>'Contact & directions','title'=>'Come, learn and serve with us.','intro'=>'Reach out about child sponsorship, courses, retreats, pilgrimages, volunteering or a visit to either of our Kerala centres.','image'=>'images/shanti-nilayam-hero.png','alt'=>'Kerala retreat surrounded by nature'])
<section class="py-24"><div class="container-site"><div class="grid gap-7 lg:grid-cols-2">
<article class="card reveal !p-8 sm:!p-10"><div class="text-xs font-bold uppercase tracking-[.2em] text-saffron">Children’s home</div><h2 class="mt-3 text-4xl font-semibold text-forest">JJK Gurukulam</h2><p class="mt-5 leading-8 text-ink/65">Kuruvikkadu, near Vattiyoorkavu<br>Thiruvananthapuram, Kerala, India</p><div class="mt-7 space-y-3 border-t border-sandal pt-6 text-sm"><p><strong class="text-maroon">From airport:</strong> approximately 15 km</p><p><strong class="text-maroon">From railway station:</strong> approximately 8.5 km</p><p><strong class="text-maroon">Local landmark:</strong> Vattiyoorkavu, then 2 km to Kuruvikkadu</p></div></article>
<article class="card reveal !p-8 sm:!p-10"><div class="text-xs font-bold uppercase tracking-[.2em] text-saffron">Retreat & learning centre</div><h2 class="mt-3 text-4xl font-semibold text-forest">Shanti Nilayam</h2><p class="mt-5 leading-8 text-ink/65">Pallippuram, P.O. Kodannur<br>Paralam Panchayath, Thrissur, Kerala, India</p><div class="mt-7 space-y-3 border-t border-sandal pt-6 text-sm"><p><strong class="text-maroon">From Thrissur station:</strong> approximately 14 km</p><p><strong class="text-maroon">From Kochi airport:</strong> approximately 1 hour 15 minutes</p><p><strong class="text-maroon">Setting:</strong> paddy fields and coconut groves</p></div></article>
</div><div class="reveal mt-8 rounded-[2rem] bg-maroon p-8 text-center text-white sm:p-12"><div class="text-xs font-bold uppercase tracking-[.2em] text-gold">Email us</div><h2 class="mt-4 text-4xl font-semibold">jjkgurukulam@gmail.com</h2><p class="mx-auto mt-4 max-w-2xl text-white/70">Tell us what you are interested in and include your preferred dates or contribution details where relevant.</p><a href="mailto:jjkgurukulam@gmail.com" class="btn-light mt-7">Write to JJK Gurukulam</a></div></div></section>
@endsection
