@extends('layouts.app')
@section('title', 'Yoga, Vedanta & Sanskrit Courses in Kerala | Shanti Nilayam')
@section('description', 'Residential traditional Yoga, Vedanta, Bhagavad Gita, Upanishad and Sanskrit courses at Shanti Nilayam Gurukulam in Kerala.')
@section('content')
@include('partials.page-hero',['eyebrow'=>'Traditional residential learning','title'=>'Study. Reflect. Discover.','intro'=>'Authentic Yoga, Vedanta and Sanskrit programs for seekers from all backgrounds, taught in the traditional Guru–Shishya lineage.','image'=>'images/inner-page-header.jpeg','alt'=>'Kerala paddy fields and coconut palms at sunset'])
<section class="py-24"><div class="container-site"><div class="reveal max-w-3xl"><div class="eyebrow">Our learning paths</div><h2 class="section-title">Timeless knowledge, <br>carefully unfolded.</h2><p class="prose-jjk mt-6">The peaceful Gurukulam atmosphere supports focused study, meditation, selfless service and genuine inner inquiry.</p></div>
<div class="mt-12 grid gap-7 lg:grid-cols-3">
@foreach([
['Traditional Yoga','Yoga is a holistic discipline that brings balance to body, mind and emotions. Classes include asana, pranayama, meditation, relaxation, chanting and devotional prayer.','Suitable for beginners and experienced practitioners'],
['Vedanta & Bhagavad Gita','Study the knowledge of the Self through Bhagavad Gita, Upanishads, foundational Vedanta, Sanskrit chanting and contemplative practices.','Authentic Arsha Vidya teaching methodology'],
['Sanskrit','Learn the refined language of the Vedas, Upanishads, Puranas and classical Indian knowledge systems through three progressive levels.','Two-week intensive courses at each level']
] as $item)<article class="card reveal flex flex-col"><div class="text-sm font-bold uppercase tracking-[.18em] text-saffron">Residential course</div><h2 class="mt-4 text-3xl font-semibold text-forest">{{ $item[0] }}</h2><p class="mt-5 flex-1 leading-8 text-ink/70">{{ $item[1] }}</p><div class="mt-7 border-t border-sandal pt-5 text-sm font-bold text-maroon">{{ $item[2] }}</div></article>@endforeach
</div></div></section>
<section class="bg-sandal/60 py-24"><div class="container-site grid gap-14 lg:grid-cols-2"><div class="reveal"><div class="eyebrow">Sanskrit curriculum</div><h2 class="section-title">From first letters to scripture.</h2><p class="prose-jjk mt-6">Students who sincerely complete all three levels gradually develop the ability to read and understand Sanskrit independently. Class sizes remain limited to preserve personal guidance and a traditional learning atmosphere.</p></div><div class="space-y-4">
@foreach([['01','Introduction','Alphabet, vowels, consonants, combined letters, pronunciation and basic reading.'],['02','Intermediate','Useful vocabulary, sentence formation, simple conversation, reading and speaking confidence.'],['03','Advanced','Grammar, seven cases, sentence construction and selected verses from Bhagavad Gita Chapter 2.']] as $level)<div class="card reveal !p-6 sm:flex sm:gap-6"><div class="font-serif text-4xl font-bold text-gold">{{ $level[0] }}</div><div><h3 class="text-2xl font-semibold text-forest">{{ $level[1] }}</h3><p class="mt-2 leading-7 text-ink/65">{{ $level[2] }}</p></div></div>@endforeach
</div></div></section>
<section class="py-24"><div class="container-site"><div class="reveal max-w-3xl"><div class="eyebrow">Sacred journeys</div><h2 class="section-title">Pilgrimages across India.</h2><p class="prose-jjk mt-6">A Yaatra is more than travel. It is a chance to meet change with patience, purify the mind and encounter places that have inspired seekers for millennia.</p></div><div class="mt-12 grid gap-6 md:grid-cols-3">
@foreach([['Himalayan Yaatra','Delhi · Haridwar · Rishikesh · Uttarkashi · Gangotri · Yamunotri · Kedarnath · Badrinath'],['North India Yaatra','Mathura · Vrindavan · Agra · Prayagraj · Varanasi · Bodh Gaya · Gaya · Kolkata'],['South India Yaatra','Kanyakumari · Suchindram · Chidambaram · Palani · Madurai · Rameshwaram · Tiruvannamalai · Coimbatore']] as $trip)<div class="reveal rounded-3xl bg-forest p-8 text-white"><h3 class="text-3xl font-semibold">{{ $trip[0] }}</h3><p class="mt-5 leading-8 text-white/65">{{ $trip[1] }}</p></div>@endforeach
</div><div class="reveal mt-12 rounded-3xl bg-maroon px-8 py-9 text-white sm:flex sm:items-center sm:justify-between"><div><h3 class="text-3xl font-semibold">Interested in a course or Yaatra?</h3><p class="mt-2 text-white/70">Contact us for upcoming dates, availability and practical details.</p></div><a href="{{ route('contact') }}" class="btn-light mt-6 sm:mt-0">Enquire now</a></div></div></section>
@endsection
