@extends('layouts.app')
@section('title', 'Children’s Gurukulam in Thiruvananthapuram | JJK Gurukulam Trust')
@section('description', 'Learn about JJK Gurukulam, its history, value-based education, daily schedule and nurturing home for underprivileged boys in Kerala.')
@section('content')
@include('partials.page-hero',['eyebrow'=>'JJK Children’s Gurukulam · Since 2006','title'=>'A nurturing home for learning and life.','intro'=>'Education, care and Indian values come together in a secure Gurukulam environment in Vattiyoorkavu, Thiruvananthapuram.','image'=>'images/gurukulam-hero.png','alt'=>'Traditional Gurukulam learning in Kerala'])
<section class="py-24"><div class="container-site grid gap-14 lg:grid-cols-[1.15fr_.85fr]">
    <div class="reveal"><div class="eyebrow">The Gurukulam tradition</div><h2 class="section-title">Where teacher, student and values share one home.</h2><div class="prose-jjk mt-7">
        <p>A Gurukulam is a traditional place of learning where the teacher and students live together and study the scriptures. The word Guru means “teacher” and Kulam means “home”.</p>
        <p>In ancient India, it was customary for children, at the age of seven or eight, to stay with the Guru (teacher/master) for about twelve years to study the scriptures and receive holistic education. Today, it is increasingly recognized that such a system is one of the most effective ways to impart knowledge and values to children. This sacred tradition continues to be preserved at JJK Gurukulam.</p>
        <p>The name Janaka Janani Kripa is deeply meaningful: Janaka means “father”, Janani means “mother” and Kripa means “mercy” or “compassion”. Together, Janaka Janani Kripa signifies the compassion and blessings of both father and mother.</p>
        <p>JJK Gurukulam was inaugurated on 16th April 2006 by Swami Dayananda Saraswati in the presence of Uthradom Thirunal Marthanda Varma, the former titular Maharaja of Travancore and head of the Travancore Royal Family. The land and building for the Gurukulam were generously donated by a devotee.</p>
        <p>Swami Dayananda Saraswati, the world-renowned traditional teacher of Vedanta philosophy, is the inspiration behind this care home. It is one of the rare places where the traditional teaching of Yoga, Vedanta, and Sanskrit continues in an authentic manner.</p>
        <p>We select children from economically disadvantaged families, where often one or both parents are absent or unable to provide proper care and education due to difficult circumstances. Along with shelter, clothing, books, and nutritious vegetarian food, we provide value-based education and a nurturing environment. The children attend a nearby public school for their formal education.</p>
        <p>The daily schedule at the Gurukulam includes Hatha Yoga classes, chanting of Vishnu Sahasranamam in the early morning and evening, and the study of Sanskrit, Bhagavad Gita, Lalita Sahasranamam, and Vedic chanting such as Purusha Suktam, Sri Suktam, Rudram, and Chamakam.</p>
        <p>Recognizing the importance of the English language in today’s world, we provide special English tuition to help the children read, write, and communicate effectively in English. The children also maintain regular contact with their families and spend their school holidays at home.</p>
    </div></div>
    <aside class="card reveal bg-forest !p-9 text-white"><div class="text-gold">Our guiding prayer</div><blockquote class="mt-5 font-serif text-4xl leading-tight">“Tamaso Ma Jyotir Gamaya”</blockquote><p class="mt-4 text-white/70">Lead us from darkness to light.</p><div class="mt-8 h-px bg-white/15"></div><p class="mt-8 leading-7 text-white/75">Rather than complain about darkness, we believe in lighting a candle.</p>
    <div class="text-xs font-bold uppercase tracking-[.2em] text-gold mt-8">Location</div>
    <p class="mt-8">The JJK Gurukulam is located in Thiruvananthapuram, at Vattiyoorkavu, a serene and picturesque area surrounded by coconut trees. Thiruvananthapuram (Trivandrum) is an ancient city with a rich history dating back to 1000 BC. It became the capital of the Kingdom of Travancore in 1750. The name “Thiruvananthapuram” is derived from the words Thiru-Anantha-Puram, meaning “the city of Anantha” or “the abode of the sacred serpent Anantha” upon whom Lord Vishnu, the preserver in the Hindu Trinity, reclines.</p>
    <p>Thiruvananthapuram, the capital city of Kerala, is situated on the southwestern coast of India near the southern tip of the mainland. It is a beautiful seaside city built across seven hills. One of its most iconic landmarks is the Sri Padmanabhaswamy Temple, a magnificent temple believed to be nearly 2000 years old.</p>
    <div class="text-xs font-bold uppercase tracking-[.2em] text-gold mt-8">How to Reach Our Gurukulam:</div>
    <p class="mt-8">Upon arriving in Thiruvananthapuram, you may take a taxi or an auto-rickshaw to reach the Gurukulam.</p>
    <p class="mt-8">By Air:<br>
JJK Gurukulam is approximately 15 km from Thiruvananthapuram International Airport. The nearest well-known locality is Vattiyoorkavu. From Vattiyoorkavu, the Gurukulam is about 2 km away, in a place called Kuruvikkadu.<br>
By Train:<br>
We are located about 8.5 km from Thiruvananthapuram Railway Station. The nearest well-known locality is Vattiyoorkavu. From there, the Gurukulam is just 2 km away, in Kuruvikkadu.
</p>
    </aside>
</div></section>
<section class="bg-sandal/60 py-24"><div class="container-site"><div class="reveal max-w-3xl"><div class="eyebrow">Learning & wellbeing</div><h2 class="section-title">A complete foundation for every child.</h2></div><div class="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
@foreach([['Formal Education','Children attend a nearby public school and receive dedicated English tuition.'],['Spiritual Learning','Sanskrit, Bhagavad Gita, Vishnu Sahasranamam and traditional Vedic chanting.'],['Healthy Living','Nutritious vegetarian meals, Hatha Yoga, play and a disciplined daily rhythm.'],['A Secure Home','Shelter, clothing, books, healthcare and compassionate guidance.'],['Family Connection','Regular contact with families and school holidays spent at home.'],['Character & Seva','Dharma, meditation, self-discipline and Karma Yoga in daily life.']] as $item)
<div class="card reveal"><h3 class="text-2xl font-semibold text-forest">{{ $item[0] }}</h3><p class="mt-3 leading-7 text-ink/65">{{ $item[1] }}</p></div>@endforeach
</div></div></section>
<section class="py-24"><div class="container-site grid gap-14 lg:grid-cols-2"><div class="reveal"><div class="eyebrow">A day at JJK</div><h2 class="section-title">Discipline with warmth.</h2><p class="prose-jjk mt-6">From dawn prayer to evening study, each day creates space for learning, service, movement and rest.</p></div><div class="reveal grid gap-0 overflow-hidden rounded-3xl border border-saffron/15 bg-white shadow-xl shadow-black/5">
@foreach([['5:00 am','Wake up & bath'],['5:30 am','Hatha Yoga'],['6:00 am','Morning prayer'],['6:45 am','Karma Yoga'],['7:15 am','Study'],['8:15 am','Breakfast'],['9:00 am','School'],['3:30 pm','Return, tea & play'],['6:00 pm','Evening prayer & chanting'],['7:15 pm','Dinner'],['8:00 pm','Study'],['9:00 pm','Bedtime']] as $slot)
<div class="grid grid-cols-[100px_1fr] border-b border-sandal px-6 py-3.5 last:border-0"><strong class="text-maroon">{{ $slot[0] }}</strong><span class="text-ink/70">{{ $slot[1] }}</span></div>@endforeach
</div></div></section>
<section class="bg-forest py-20 text-white"><div class="container-site grid gap-10 lg:grid-cols-2"><div><div class="text-xs font-bold uppercase tracking-[.2em] text-gold">Visit us</div><h2 class="mt-3 text-4xl font-semibold">Vattiyoorkavu, Thiruvananthapuram</h2><p class="mt-5 leading-8 text-white/70">Our Gurukulam is in peaceful Kuruvikkadu, surrounded by coconut trees, approximately 15 km from Thiruvananthapuram International Airport and 8.5 km from the railway station.</p></div><div class="flex items-end lg:justify-end"><a class="btn-light" href="{{ route('contact') }}">Travel details & contact</a></div></div></section>
@endsection
