@extends('layouts.app')
@section('title', 'Shanti Nilayam Retreat Home | Yoga & Vedanta in Kerala')
@section('description', 'Shanti Nilayam in Thrissur offers residential Yoga, Vedanta, Sanskrit, meditation and spiritual retreats in peaceful rural Kerala.')
@section('content')
@include('partials.page-hero',['eyebrow'=>'JJK Gurukulam Retreat Home · Thrissur','title'=>'An abode of peace.','intro'=>'A traditional learning centre for Yoga, Vedanta and Sanskrit, set among paddy fields and coconut groves in rural Kerala.','image'=>'images/shanti-nilayam-hero.png','alt'=>'Shanti Nilayam retreat home in rural Kerala'])
<section class="py-24"><div class="container-site grid items-center gap-16 lg:grid-cols-2"><div class="reveal"><div class="eyebrow">Space for inner growth</div><h2 class="section-title">Step away from noise. Return to yourself.</h2><div class="prose-jjk mt-7"><p>Shanti Nilayam is located in Pallippuram village in Thrissur, Kerala’s cultural capital. Away from the distractions of city life, it offers an ideal environment for spiritual study, reflection and transformation.</p><p>Our teachers are trained in the Arsha Vidya tradition established by Swami Dayananda Saraswati. The centre is directed by his disciple, Swami Tattvarupananda.</p><p>Courses are generally ten days long and weave together meditation, Yoga, Vedanta lectures, Sanskrit, Satsang and Karma Yoga.</p></div></div><img src="{{ asset('images/shanti-nilayam-inner.jpeg') }}" alt="Peaceful paddy fields and coconut groves near Shanti Nilayam" class="reveal aspect-square w-full rounded-[2rem] object-cover shadow-2xl"></div></section>
<section class="bg-sandal/60 py-24"><div class="container-site"><div class="mx-auto max-w-3xl text-center reveal"><div class="eyebrow justify-center before:hidden">Beyond the classroom</div><h2 class="section-title">Peace expressed as service.</h2><p class="prose-jjk mt-6">The retreat also serves nearby villages through medical assistance, health and environmental awareness, cultural classes for children and educational support.</p></div><div class="mt-12 grid gap-6 md:grid-cols-3">@foreach([['Community Care','Medical assistance and practical health awareness for local families.'],['Children’s Programs','Value-based cultural learning through stories, games and creativity.'],['Future Initiatives','Women’s empowerment programs focused on practical, sustainable skills.']] as $item)<div class="card reveal text-center"><h3 class="text-2xl font-semibold text-forest">{{ $item[0] }}</h3><p class="mt-3 leading-7 text-ink/65">{{ $item[1] }}</p></div>@endforeach</div></div></section>
<section class="py-24"><div class="container-site grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div class="reveal"><div class="eyebrow">Course rhythm</div><h2 class="section-title">A day designed for clarity.</h2><p class="prose-jjk mt-6">Meditation, prayer, Yoga, study, selfless service and Satsang create a balanced daily rhythm for reflection and inner growth.</p><div class="mt-8 flex flex-wrap gap-3"><a class="btn-primary" href="{{ route('application.create') }}">Apply for a retreat</a><a class="inline-flex items-center justify-center rounded-full border border-maroon/20 px-6 py-3.5 text-sm font-bold text-maroon transition hover:border-maroon hover:bg-maroon hover:text-white" href="{{ route('courses') }}">Explore all courses</a></div></div><div class="reveal grid gap-3 sm:grid-cols-2">
@foreach([['05:30','Wake-up'],['06:00–06:30','Japa Meditation'],['06:30–07:15','Prayer'],['07:30','Herbal Tea'],['08:00–09:45','Yoga class'],['10:00–10:30','Brunch'],['11:30–12:30','Lecture'],['13:30','Herbal Tea'],['14:00–15:00','Karma Yoga'],['16:00–17:15','Asana self-practice or nature walks'],['17:45–18:15','Japa Meditation'],['18:15–19:00','Prayer'],['19:00–19:30','Dinner'],['19:45–20:30','Satsang (Q&A)'],['21:30','Lights off']] as $slot)<div class="grid grid-cols-[120px_1fr] items-center rounded-2xl border border-saffron/15 bg-white px-5 py-4"><strong class="text-maroon">{{ $slot[0] }}</strong><span class="text-ink/65">{{ $slot[1] }}</span></div>@endforeach</div></div></section>
<section class="bg-maroon py-20 text-white"><div class="container-site flex flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><div class="text-xs font-bold uppercase tracking-[.2em] text-gold">Location</div><h2 class="mt-3 text-4xl font-semibold">Pallippuram, Kodannur, Thrissur</h2><p class="mt-4 max-w-2xl text-white/70">14 km from Thrissur Railway Station and approximately 1 hour 15 minutes from Kochi International Airport.</p></div><a href="{{ route('contact') }}" class="btn-light shrink-0">Plan your visit</a></div></section>
@endsection
