@extends('layouts.app')
@section('title', 'Support a Child | Donate to JJK Gurukulam Trust')
@section('description', 'Support meals, education, clothing and care for children at JJK Gurukulam Trust. View sponsorship options and verified bank details.')
@section('content')
@include('partials.page-hero',['eyebrow'=>'Compassion in action','title'=>'Help a child step into the light.','intro'=>'Your contribution sustains education, nutrition, healthcare and a secure home for children who deserve the opportunity to thrive.','image'=>'images/gurukulam-hero.png','alt'=>'Children studying at a Kerala Gurukulam'])
<section class="py-24"><div class="container-site grid gap-16 lg:grid-cols-[.8fr_1.2fr]"><div class="reveal"><div class="eyebrow">Yes, you can help</div><h2 class="section-title">Choose a meaningful day to give.</h2><p class="prose-jjk mt-6">A birthday, anniversary, sacred occasion or memorial day can become a day of nourishment, learning and hope at the Gurukulam.</p><p class="prose-jjk mt-5">All donations are properly acknowledged, accounted for and duly audited. Contributions are accepted in cash or kind from individuals, families, firms, organizations and companies.</p></div><div class="grid gap-4 sm:grid-cols-2">
@foreach([['₹3,000','One day food offering'],['₹3,000','Sponsor a child for one month'],['₹18,000','Sponsor a child for six months'],['₹36,000','Sponsor a child for one year'],['₹10,000','Sponsor all expenses for one day'],['₹12,500','Academics & clothing for one child/year']] as $option)<div class="card reveal !p-6"><strong class="font-serif text-4xl text-maroon">{{ $option[0] }}</strong><p class="mt-2 leading-6 text-ink/65">{{ $option[1] }}</p></div>@endforeach
</div></div></section>
<section class="bg-sandal/60 py-24"><div class="container-site"><div class="reveal max-w-3xl"><div class="eyebrow">Bank transfer details</div><h2 class="section-title">Contribute directly to the Trust.</h2><p class="mt-5 text-ink/65">Payable to <strong>JJK Gurukulam Trust, Trivandrum</strong>. Please contact us after making a transfer so we can acknowledge your contribution.</p></div><div class="mt-10 grid gap-6 lg:grid-cols-2">
@foreach([
['South Indian Bank','Ammadam, Thrissur','0003053000011682','SIBL0000003'],
['Canara Bank','Anchamada, Thiruvananthapuram','1163101054214','CNRB0001163']
] as $bank)<div class="card reveal"><h3 class="text-3xl font-semibold text-forest">{{ $bank[0] }}</h3><dl class="mt-6 grid gap-4 text-sm"><div><dt class="font-bold uppercase tracking-wider text-ink/40">Account name</dt><dd class="mt-1 text-lg">JJK Gurukulam Trust</dd></div><div><dt class="font-bold uppercase tracking-wider text-ink/40">Savings account</dt><dd class="mt-1 text-lg font-semibold text-maroon">{{ $bank[2] }}</dd></div><div><dt class="font-bold uppercase tracking-wider text-ink/40">Branch</dt><dd class="mt-1 text-lg">{{ $bank[1] }}</dd></div><div><dt class="font-bold uppercase tracking-wider text-ink/40">IFSC</dt><dd class="mt-1 text-lg font-semibold">{{ $bank[3] }}</dd></div></dl></div>@endforeach
</div><div class="reveal mt-8 rounded-3xl bg-forest p-8 text-white"><h3 class="text-2xl font-semibold">Foreign contributions</h3><p class="mt-3 text-white/70">JJK Gurukulam Trust is registered under FCRA to receive contributions from outside India. Please email <a class="font-bold text-gold underline" href="mailto:jjkgurukulam@gmail.com">jjkgurukulam@gmail.com</a> for the designated account details.</p></div></div></section>
@endsection
